cmake_minimum_required(VERSION 3.30)

if(TEST_INSTALLED_VERSION)
    project(test_sigslot_conifg_package LANGUAGES CXX)
    find_package(PalSigslot CONFIG REQUIRED)
    include(../cmake/SigslotUtils.cmake)
endif()

add_custom_target(examples COMMENT "Build all the examples.")

macro(pal_create_example target ut)
    add_executable(${target} "${ut}")
    target_link_libraries(${target} PRIVATE Pal::Sigslot)
    target_compile_options(${target} PRIVATE $<$<CXX_COMPILER_ID:MSVC>:/bigobj>)
    target_compile_definitions(${target} PRIVATE $<$<CXX_COMPILER_ID:MSVC>:_SCL_SECURE_NO_WARNINGS>)
    add_dependencies(examples ${target})
    sigslot_set_properties(${target} PRIVATE)
endmacro()

file(
    GLOB_RECURSE UNIT_TESTS
    RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cpp"
)
foreach(ex IN LISTS UNIT_TESTS)
    string(REPLACE ".cpp" "" target ${ex})
    string(REPLACE "/" "-" target ${target})

    if(target MATCHES "boost")
        if(TARGET Boost::system)
            message(STATUS "build ${target}")
            pal_create_example(${target} "${ex}")
            target_link_libraries(${target} PRIVATE Boost::system)
        endif()
    elseif(target MATCHES "qt")
        if(TARGET Qt6::Core)
            message(STATUS "build ${target}")
            pal_create_example(${target} "${ex}")
            target_link_libraries(${target} PRIVATE Qt6::Core)
            set_target_properties(${target} PROPERTIES AUTOMOC ON)
            if(TARGET QCoro6::Core AND target MATCHES "qcoro")
                target_link_libraries(${target} PRIVATE QCoro6::Core)
                target_compile_definitions(${target} PRIVATE SIGSLOT_HAVE_QCORO)
            endif()
        endif()
    else()
        message(STATUS "build ${target}")
        pal_create_example(${target} "${ex}")
    endif()
endforeach()
